// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using REST_API_GAMES.Data;

#nullable disable

namespace REST_API_GAMES.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230928215625_DBGames")]
    partial class DBGames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("REST_API_GAMES.Models.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Developer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1456296-16ea-4e11-ab71-a2d59805000d"),
                            Name = "Infinity Ward"
                        },
                        new
                        {
                            Id = new Guid("ccb4bb29-1c2c-4ba1-9605-d8349ae4abd3"),
                            Name = "4A Games"
                        });
                });

            modelBuilder.Entity("REST_API_GAMES.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Genre")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Platform")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccb4bb29-1c2c-4ba1-9605-d8349ae4abd3"),
                            Description = "Modern Warfare 3 is a first-person shooter video game much like its predecessors. Modern Warfare 3 for Microsoft Windows has dedicated server support.",
                            DeveloperId = new Guid("d1456296-16ea-4e11-ab71-a2d59805000d"),
                            Genre = 2,
                            Name = "Call of Duty: Modern Warfare 3",
                            Platform = 0,
                            PublisherId = new Guid("156b737b-1f6c-4977-bebd-c4a01307b781"),
                            Rating = 10.0,
                            Time = new DateTime(2023, 9, 28, 23, 56, 25, 492, DateTimeKind.Local).AddTicks(3536)
                        },
                        new
                        {
                            Id = new Guid("79279c60-511f-45e5-99b5-e974ba347fca"),
                            Description = "Metro 2033",
                            DeveloperId = new Guid("ccb4bb29-1c2c-4ba1-9605-d8349ae4abd3"),
                            Genre = 2,
                            Name = "Metro 2033",
                            Platform = 1,
                            PublisherId = new Guid("2cb2beed-c229-4c9f-9a08-df385ec0d548"),
                            Rating = 9.0,
                            Time = new DateTime(2023, 9, 28, 23, 56, 25, 492, DateTimeKind.Local).AddTicks(3613)
                        });
                });

            modelBuilder.Entity("REST_API_GAMES.Models.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = new Guid("156b737b-1f6c-4977-bebd-c4a01307b781"),
                            Name = "Activision"
                        },
                        new
                        {
                            Id = new Guid("2cb2beed-c229-4c9f-9a08-df385ec0d548"),
                            Name = "THQ"
                        });
                });

            modelBuilder.Entity("REST_API_GAMES.Models.Game", b =>
                {
                    b.HasOne("REST_API_GAMES.Models.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId");

                    b.HasOne("REST_API_GAMES.Models.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId");

                    b.Navigation("Developer");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("REST_API_GAMES.Models.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("REST_API_GAMES.Models.Publisher", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
